// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// funcSimX
NumericMatrix funcSimX(NumericVector coef, NumericMatrix buffMat);
RcppExport SEXP unsystation_funcSimX(SEXP coefSEXP, SEXP buffMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type buffMat(buffMatSEXP);
    __result = Rcpp::wrap(funcSimX(coef, buffMat));
    return __result;
END_RCPP
}
// func_coef
NumericVector func_coef(NumericVector z, int scale);
RcppExport SEXP unsystation_func_coef(SEXP zSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type scale(scaleSEXP);
    __result = Rcpp::wrap(func_coef(z, scale));
    return __result;
END_RCPP
}
// funcRes
List funcRes(NumericMatrix yMat, int M, int minLength, NumericVector probVec, IntegerVector topCand, IntegerVector bottomCand, NumericVector var);
RcppExport SEXP unsystation_funcRes(SEXP yMatSEXP, SEXP MSEXP, SEXP minLengthSEXP, SEXP probVecSEXP, SEXP topCandSEXP, SEXP bottomCandSEXP, SEXP varSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type yMat(yMatSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type minLength(minLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probVec(probVecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type topCand(topCandSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bottomCand(bottomCandSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var(varSEXP);
    __result = Rcpp::wrap(funcRes(yMat, M, minLength, probVec, topCand, bottomCand, var));
    return __result;
END_RCPP
}
// funcResVar
NumericMatrix funcResVar(NumericMatrix yMat, NumericMatrix seMat, NumericVector tmpVar);
RcppExport SEXP unsystation_funcResVar(SEXP yMatSEXP, SEXP seMatSEXP, SEXP tmpVarSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type yMat(yMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type seMat(seMatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmpVar(tmpVarSEXP);
    __result = Rcpp::wrap(funcResVar(yMat, seMat, tmpVar));
    return __result;
END_RCPP
}
// funcApplyVar
NumericMatrix funcApplyVar(NumericMatrix nullStatMat, int maxLevel, int Msq);
RcppExport SEXP unsystation_funcApplyVar(SEXP nullStatMatSEXP, SEXP maxLevelSEXP, SEXP MsqSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type nullStatMat(nullStatMatSEXP);
    Rcpp::traits::input_parameter< int >::type maxLevel(maxLevelSEXP);
    Rcpp::traits::input_parameter< int >::type Msq(MsqSEXP);
    __result = Rcpp::wrap(funcApplyVar(nullStatMat, maxLevel, Msq));
    return __result;
END_RCPP
}
