# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

funcSimX <- function(coef, buffMat) {
    .Call('unsystation_funcSimX', PACKAGE = 'unsystation', coef, buffMat)
}

func_coef <- function(z, scale) {
    .Call('unsystation_func_coef', PACKAGE = 'unsystation', z, scale)
}

funcRes <- function(yMat, M, minLength, probVec, topCand, bottomCand, var) {
    .Call('unsystation_funcRes', PACKAGE = 'unsystation', yMat, M, minLength, probVec, topCand, bottomCand, var)
}

funcResVar <- function(yMat, seMat, tmpVar) {
    .Call('unsystation_funcResVar', PACKAGE = 'unsystation', yMat, seMat, tmpVar)
}

funcApplyVar <- function(nullStatMat, maxLevel, Msq) {
    .Call('unsystation_funcApplyVar', PACKAGE = 'unsystation', nullStatMat, maxLevel, Msq)
}

